parameters:
    downloads_dir: '../downloads'

services:
    meta:
        class:     \ShvetsGroup\Service\Meta

    jobs:
        class:     \ShvetsGroup\Service\Jobs
        arguments: [ @proxy ]
        calls:
          - [ setContainer, [ @service_container ] ]

    downloader:
        class:     \ShvetsGroup\Service\Downloader
        arguments: [ '%downloads_dir%', @identity, @proxy ]

    identity:
        class:     \ShvetsGroup\Service\Identity

    proxy:
        class:     \ShvetsGroup\Service\Proxy

    discover_command:
        class:     \ShvetsGroup\Command\DiscoverCommand
        arguments: [ @jobs, @meta ]

    update_command:
       class:     \ShvetsGroup\Command\UpdateCommand
       arguments: [ @jobs, @meta ]

    download_command:
       class:     \ShvetsGroup\Command\DownloadCommand
       arguments: [ @jobs ]

    check_command:
       class:     \ShvetsGroup\Command\CheckCommand
       arguments: [ '%downloads_dir%', @jobs ]

    dump_command:
       class:     \ShvetsGroup\Command\DumpCommand
       arguments: [ '%downloads_dir%', @jobs ]

    cleanup_command:
       class:     \ShvetsGroup\Command\CleanupCommand
       arguments: [ @jobs ]



