parameters:
    downloads_dir: '../downloads'
    use_proxy: 0
    max_crawl_date: 2014-10-18
    db:
      database: radadata
      username: root
      password: root
      host: localhost
      port: 3306
      driver: mysql
      prefix:
      charset: utf8
      collation: utf8_unicode_ci
    aws:
      version: latest
      profile: default
      region: eu-west-1
      server_keys_dir: 'app/servers'
      ImageId: 'ami-4a268b3d'
      InstanceType: 't1.micro'
      KeyName: 'AMI'
      SecurityGroupIds: 'sg-f5a19481'
      SpotPrice: '0.01'
    proxy_list:
      - 192.161.160.246:8800
      - 192.161.160.130:8800
      - 170.130.63.250:8800
      - 170.130.63.127:8800
      - 173.234.59.224:8800
      - 173.234.59.44:8800
      - 173.234.226.231:8800
      - 173.234.59.53:8800
      - 173.234.226.204:8800
      - 173.234.59.9:8800

imports:
  - { resource: common.yml }