parameters:
    downloads_dir: '../downloads'
    use_proxy: 1
    db:
      database: radadata
      username: root
      password: root
      host: localhost
      port: 3306
      driver: mysql
      prefix:
      charset: utf8
      collation: utf8_unicode_ci
    aws:
      version: latest
      profile: default
      region: eu-west-1
      server_keys_dir: 'app/servers'


services:
    database:
        class:     \ShvetsGroup\Service\Database
        arguments: [ '%db%' ]

    meta:
        class:     \ShvetsGroup\Service\Meta

    jobs_manager:
        class:     \ShvetsGroup\Service\JobsManager
        arguments: [ @proxy ]
        calls:
          - [ setContainer, [ @service_container ] ]

    downloader:
        class:     \ShvetsGroup\Service\Downloader
        arguments: [ '%downloads_dir%', @identity, @proxy ]

    identity:
        class:     \ShvetsGroup\Service\Identity

    proxy:
        class:     \ShvetsGroup\Service\Proxy
        arguments: [ '%aws%', '%use_proxy%' ]

    status_command:
       class:     \ShvetsGroup\Command\StatusCommand
       arguments: [ '%downloads_dir%', @jobs_manager, @proxy ]

    discover_command:
        class:     \ShvetsGroup\Command\DiscoverCommand
        arguments: [ @jobs_manager, @meta ]

    download_command:
       class:     \ShvetsGroup\Command\DownloadCommand
       arguments: [ @jobs_manager ]

    check_command:
       class:     \ShvetsGroup\Command\CheckCommand
       arguments: [ '%downloads_dir%', @jobs_manager ]

    dump_command:
       class:     \ShvetsGroup\Command\DumpCommand
       arguments: [ '%downloads_dir%', @jobs_manager ]

    cleanup_command:
       class:     \ShvetsGroup\Command\CleanupCommand
       arguments: [ @jobs_manager ]

    cron_command:
       class:     \ShvetsGroup\Command\CronCommand
       arguments: [ @discover_command, @download_command, @jobs_manager, @proxy ]

